### ISSUE TITLE
New icons in O2

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-icons#114]
### Context
If you think there is a icon missing in Mística and you feel it is worthy to create it globally and therefore any team could use it, please follow the process below so we can integrate this new icon from Design to Development.

**Have you read the [Contributing Guidelines on Mística](https://brandfactory.telefonica.com/document/1846#/contribute-to-mistica/components-request)?**
Yes

---
Se han subido nuevos iconos con sus 3 pesos diferentes en la libería de iconos de O2. Los iconos nuevos son:
- [x] Language
	- [x] In Figma
	- [x] Implemented	
- [x] Connected car
	- [x] In Figma
	- [x] Implemented	
- [x] Fusion
	- [x] In Figma
	- [x] Implemented	
- [x] Wallet Id
	- [x] In Figma
	- [x] Implemented	
- [x] Non binary toilet
	- [x] In Figma
	- [x] Implemented	
- [x] Non binary toilet inclusive
	- [x] In Figma
	- [x] Implemented	
- [x] queue
	- [x] In Figma
	- [x] Implemented	
- [x] cloakroom
	- [x] In Figma
	- [x] Implemented	
- [x] coffee-tea
	- [x] In Figma
	- [x] Implemented	
- [x] conference
	- [x] In Figma
	- [x] Implemented	
- [x] desk
	- [x] In Figma
	- [x] Implemented	
- [x] exit
	- [x] In Figma
	- [x] Implemented	
- [x] floorplan
	- [x] In Figma
	- [x] Implemented	
- [x] report
	- [x] In Figma
	- [x] Implemented	
- [x] view-360
	- [x] In Figma
	- [x] Implemented	
- [x] zone
	- [x] In Figma
	- [x] Implemented	
- [x] cancellation
	- [x] In Figma
	- [x] Implemented

**Comment by yceballost** [comment]
Solo existe una correspondencia de estos iconos nuevos, el de wallet. El resto no lo integraremos en mística hasta que se necesiten. 

@AnaMontes11

**Comment by AnaMontes11** [comment]
Revisado, por mi parte _wallet icon_ para integrar ya, perfecto!

**Comment by yceballost** [comment]
integrated in mistica-web
