### ISSUE TITLE
Improve icon weight in O2

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-icons#213]
### Describe or attach a screenshot of the bug
O2 España ha detectado que hay varios iconos que no están alineados con el grosor de el resto de iconos del pack

### Name of the icon
Please, tell us what is the name of the bugged icon:
- [x] chevron-right-regular
- [x] chevron-down-regular
- [x] chevron-left-regular
- [x] chevron-up-regular
- [x] add-more-regular
- [x] close-regular
---
- [x] add-more-light
- [x] close-light
- [x] chevron-down-light
- [x] chevron-left-light
- [x] chevron-right-light
- [x] chevron-up-light
---
- [x] add-more-filled

### Additional info?
Mantener tamaño solo cambiar grosor

**Comment by aweell** [comment]
Fixed weight in additional icons:

| Name | Current | Updated |
| :----- | :------ | :------ |
| cocktail-regular | ![cocktail-regular](https://user-images.githubusercontent.com/44420072/171826716-17916138-c0aa-46e7-8f96-7d1044507602.svg)| ![cocktail-regular](https://user-images.githubusercontent.com/44420072/171826742-9c0d4549-86ad-421e-af12-fd84d6fa5e87.svg)|
| check-regular |![check-regular](https://user-images.githubusercontent.com/44420072/171827266-06fff3f3-9822-42ca-af5c-115ea7e8ef86.svg)| ![check-regular](https://user-images.githubusercontent.com/44420072/171827295-2094d26f-fc54-4737-84a0-dc42a6b7975a.svg)|
